### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by acgtyrant** [kuangliu/pytorch-retinanet#13]
I would like to close my fork.

**Comment by kuangliu** [comment]
Go ahead. 
I don't like licences. :)

**Comment by tarrencev** [comment]
@kuangliu I would like to contribute but can't do so without a license. Would you consider adding one?

**Comment by acgtyrant** [comment]
@tarrencev I think his license is wtfpl.

**Comment by tarrencev** [comment]
@acgtyrant that would be great. Is it listed somewhere I'm missing?

**Comment by acgtyrant** [comment]
No listed anywhere.
