### ISSUE TITLE
index out of range 

### ISSUE THREAD

**Issue by cherryxiongyw** [kuangliu/pytorch-retinanet#24]
When I use this model to train coco2017, the num_classes is set to 80.But there is an error likes this:
`RuntimeError: index out of range at /opt/conda/conda-bld/pytorch_1503966894950/work/torch/lib/TH/generic/THTensorMath.c:277`
which is occured at “pytorch-retinanet/utils.py", line 230, in one_hot_embedding” `return y[labels]`.
So what happened,why?How can I solve this problem?

**Comment by kuangliu** [comment]
coco2017 has 90 classes.
