### ISSUE TITLE
encoder 

### ISSUE THREAD

**Issue by njtuzzy** [kuangliu/pytorch-retinanet#4]
@kuangliu , i am using pytorch 0.12, but i find that in DataEncoder class, the encoder function, "boxes=boxes[max_idx]" can not work, do you mean that this operation can enlarge the size of boxes tensor to anchor size?  I can not use this operation due to the different version??

Thanks

**Comment by kuangliu** [comment]
Update to PyTorch 0.2.0 with advanced indexing support.

**Comment by njtuzzy** [comment]
Glad to know it, thanks

**Comment by kuangliu** [comment]
Close this now, feel free to reopen.
