### ISSUE TITLE
cls_loss is NAN    

### ISSUE THREAD

**Issue by Brozhao** [kuangliu/pytorch-retinanet#47]

**Comment by Brozhao** [comment]
loc_loss: 0.096 | cls_loss: 49.812 | train_loss: 49.907 | avg_loss: 312.096
loc_loss: 0.102 | cls_loss: 34.575 | train_loss: 34.676 | avg_loss: 292.280
loc_loss: 0.093 | cls_loss: 22.649 | train_loss: 22.742 | avg_loss: 274.311
loc_loss: 0.095 | cls_loss: 603.826 | train_loss: 603.921 | avg_loss: 294.912
loc_loss: 0.097 | cls_loss: 96.089 | train_loss: 96.186 | avg_loss: 283.222
loc_loss: 0.100 | cls_loss: 268.645 | train_loss: 268.745 | avg_loss: 282.418
loc_loss: 0.246 | cls_loss: 185.135 | train_loss: 185.381 | avg_loss: 277.310
loc_loss: 0.574 | cls_loss: 3271.793 | train_loss: 3272.367 | avg_loss: 427.063
loc_loss: 14.899 | cls_loss: 4664092.368 | train_loss: 4664107.500 | avg_loss: 222507.084
loc_loss: 0.096 | cls_loss: 1018231725413.010 | train_loss: 1018231717888.000 | avg_loss: 46283472297.126
loc_loss: 0.094 | cls_loss: 9635243732500480.000 | train_loss: 9635243732500480.000 | avg_loss: 418967911690913.750
loc_loss: 0.096 | cls_loss: 35978558609519793754739982653718528.000 | train_loss: 35978558370880749703701422304919552.000 | avg_loss: 1499106598786698000397684646608896.000
loc_loss: 0.101 | cls_loss: nan | train_loss: nan | avg_loss: nan
loc_loss: 0.101 | cls_loss: nan | train_loss: nan | avg_loss: nan
loc_loss: 0.093 | cls_loss: nan | train_loss: nan | avg_loss: nan
loc_loss: 0.102 | cls_loss: nan | train_loss: nan | avg_loss: nan
loc_loss: 0.118 | cls_loss: nan | train_loss: nan | avg_loss: nan
loc_loss: 0.102 | cls_loss: nan | train_loss: nan | avg_loss: nan
loc_loss: 0.114 | cls_loss: nan | train_loss: nan | avg_loss: nan

**Comment by Brozhao** [comment]
how can I solve that 
would anyone help me

**Comment by banjuanshua** [comment]
I have fixed this bug, you can see it in my pull request.

**Comment by Brozhao** [comment]
This problem has been solved according to your method.Thank you！

**Comment by Brozhao** [comment]
> I have fixed this bug, you can see it in my pull request.

NAN of the loss haves never appeared,but the mAP is almost zero.
